services:
  - type: web
    name: tea-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromGroup: false
      - key: PORT
        value: 5000
